#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

#runApplication blockMesh
#runApplication decomposePar 
runParallel $(getApplication)
#runApplication reconstructPar -time 63:70
#rm -r processor*
#rm -r log.*
#------------------------------------------------------------------------------
