#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

runApplication blockMesh 
runApplication checkMesh 
runApplication decomposePar 
runParallel $(getApplication) 
runApplication reconstructPar -time    17.01,18.22,19.44,20.66,21.87
postProcess -func sampleDict  -time    17.01,18.22,19.44,20.66,21.87
rm -r processor*
rm -r log.*
gnuplot gnuplot/tauPlot
gnuplot gnuplot/Uplot 
#python3 logplot.py


#------------------------------------------------------------------------------
